#!/bin/sh

    echo 'Styling, testing and building your project before committing'

    # check prettier standards
    npm run check-format || (
        echo 'Prettier check Failed. Run npm run format, add changes and try commit again.';
        false;
    )

    # check eslint standards
    npm run check-lint || (
        echo 'ESLint check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
    )

    # check tsconfig
    npm run check-types || (
        echo 'TypeScript check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
    )

    npm run build || (
        echo 'Your build failed, view the errors above',
        false
    )

    echo 'Success committing 🚀'#!/bin/sh

    echo 'Styling, testing and building your project before committing'

    # check prettier standards
    npm run check-format || (
        echo 'Prettier check Failed. Run npm run format, add changes and try commit again.';
        false;
    )

    # check eslint standards
    npm run check-lint || (
        echo 'ESLint check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
    )

    # check tsconfig
    npm run check-types || (
        echo 'TypeScript check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
    )

    npm run build || (
        echo 'Your build failed, view the errors above',
        false
    )

    echo 'Success committing 🚀'